"use client";

import { useState } from "react";
import { toast } from "sonner";
import { setTournamentStatus, updateTournamentSettings } from "@/lib/admin/tournaments";
import type { Tournament } from "@/types/tournament";

export function TournamentSettings({ tournament, onSaved }: { tournament: Tournament; onSaved: () => void }) {
  const [values, setValues] = useState({ title: tournament.title, description: tournament.description ?? "", banner_url: tournament.banner_url ?? "", rules: tournament.rules ?? "", registration_open_at: tournament.registration_open_at.slice(0, 16), registration_close_at: tournament.registration_close_at.slice(0, 16), checkin_open_at: tournament.checkin_open_at.slice(0, 16), checkin_close_at: tournament.checkin_close_at.slice(0, 16), start_time: tournament.start_time.slice(0, 16), status: tournament.status });
  const [busy, setBusy] = useState(false);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { await updateTournamentSettings(tournament.id, { title: values.title, description: values.description, banner_url: values.banner_url || null, rules: values.rules, registration_open_at: new Date(values.registration_open_at).toISOString(), registration_close_at: new Date(values.registration_close_at).toISOString(), checkin_open_at: new Date(values.checkin_open_at).toISOString(), checkin_close_at: new Date(values.checkin_close_at).toISOString(), start_time: new Date(values.start_time).toISOString() }); if (values.status !== tournament.status) await setTournamentStatus(tournament.id, values.status); toast.success("Tournament settings saved"); onSaved(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save settings"); } finally { setBusy(false); } };
  const field = (name: keyof typeof values, label: string, multiline = false) => <label className="field"><span>{label}</span>{multiline ? <textarea rows={3} value={values[name]} onChange={(event) => setValues((current) => ({ ...current, [name]: event.target.value }))} /> : <input value={values[name]} type={name.endsWith("_at") || name === "start_time" ? "datetime-local" : "text"} onChange={(event) => setValues((current) => ({ ...current, [name]: event.target.value }))} />}</label>;
  return <form className="grid gap-3 sm:grid-cols-2" onSubmit={save}>{field("title", "Title")}{field("banner_url", "Banner URL")}{field("description", "Description", true)}{field("rules", "Rules", true)}{field("registration_open_at", "Registration opens")}{field("registration_close_at", "Registration closes")}{field("checkin_open_at", "Check-in opens")}{field("checkin_close_at", "Check-in closes")}{field("start_time", "Start time")}<label className="field"><span>Status</span><select value={values.status} onChange={(event) => setValues((current) => ({ ...current, status: event.target.value as typeof current.status }))}>{["draft", "open", "registration_closed", "check_in", "ongoing", "completed", "cancelled"].map((status) => <option key={status} value={status}>{status}</option>)}</select></label><button className="btn-primary sm:col-span-2" disabled={busy}>{busy ? "Saving…" : "Save settings"}</button></form>;
}
