"use client";

import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { toast } from "sonner";
import { submitReport } from "@/lib/reports/data";
import type { ReportCategory } from "@/types/reports";

const categories: Array<[ReportCategory, string]> = [["no_show", "No Show"], ["wrong_player", "Wrong Player"], ["fake_score", "Fake Score"], ["toxic_behaviour", "Toxic Behaviour"], ["cheating", "Cheating / Suspicious Activity"], ["other", "Other"]];
export function ReportPlayerModal({ reportedUserId, tournamentId = null, matchId = null, teamId = null }: { reportedUserId: string; tournamentId?: string | null; matchId?: string | null; teamId?: string | null }) {
  const [open, setOpen] = useState(false); const [category, setCategory] = useState<ReportCategory>("other"); const [description, setDescription] = useState(""); const [evidenceUrl, setEvidenceUrl] = useState("");
  const report = useMutation({ mutationFn: () => { if (description.trim().length < 10) throw new Error("Please describe the issue in at least 10 characters."); return submitReport({ reportedUserId, tournamentId, matchId, teamId, category, description, evidenceUrl }); }, onSuccess: () => { toast.success("Report submitted"); setOpen(false); setDescription(""); setEvidenceUrl(""); }, onError: (error: Error) => toast.error(error.message.replaceAll("_", " ")) });
  if (!open) return <button className="rounded-lg border border-arena-border px-3 py-2 text-sm text-arena-muted hover:text-arena-text" onClick={() => setOpen(true)}>Report player</button>;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><form className="w-full max-w-lg rounded-2xl border border-arena-border bg-arena-surface p-6 shadow-2xl" onSubmit={(event) => { event.preventDefault(); report.mutate(); }}><div className="flex items-center justify-between"><h2 className="font-display text-2xl font-semibold text-arena-text">Report player</h2><button type="button" className="text-arena-muted" onClick={() => setOpen(false)}></button></div><p className="mt-2 text-sm text-arena-muted">Reports are reviewed by tournament moderators.</p><select className="input-field mt-5 w-full" value={category} onChange={(event) => setCategory(event.target.value as ReportCategory)}>{categories.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><textarea className="input-field mt-3 min-h-32 w-full" placeholder="Describe what happened…" value={description} onChange={(event) => setDescription(event.target.value)} required /><input className="input-field mt-3 w-full" placeholder="Evidence link (optional)" value={evidenceUrl} onChange={(event) => setEvidenceUrl(event.target.value)} /><div className="mt-5 flex justify-end gap-2"><button type="button" className="rounded-lg border border-arena-border px-4 py-2 text-sm text-arena-muted" onClick={() => setOpen(false)}>Cancel</button><button className="btn-primary px-4 py-2 text-sm" disabled={report.isPending}>{report.isPending ? "Submitting…" : "Submit report"}</button></div></form></div>;
}
