-- Phase 11 foundation. Local migration only; do not push automatically.
alter table public.profiles add column if not exists favorite_game text default 'VALORANT';
alter table public.profiles add column if not exists trust_score integer not null default 50 check (trust_score between 0 and 100);
alter table public.profiles add column if not exists current_rank text;
alter table public.teams add column if not exists slug text;
alter table public.teams add column if not exists banner_url text;
alter table public.teams add column if not exists region text;
update public.teams set slug = lower(regexp_replace(name, '[^a-zA-Z0-9]+', '-', 'g')) || '-' || left(replace(id::text, '-', ''), 8) where slug is null;
alter table public.teams alter column slug set not null;
create unique index if not exists teams_slug_idx on public.teams(slug);

create table if not exists public.seasons (id uuid primary key default gen_random_uuid(), name text not null unique, starts_at timestamptz not null, ends_at timestamptz not null, created_at timestamptz not null default now());
create table if not exists public.player_season_rankings (season_id uuid not null references public.seasons(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, ranking_points integer not null default 0, matches_played integer not null default 0, wins integer not null default 0, championships integer not null default 0, primary key (season_id, user_id));
create table if not exists public.team_season_rankings (season_id uuid not null references public.seasons(id) on delete cascade, team_id uuid not null references public.teams(id) on delete cascade, ranking_points integer not null default 0, matches_played integer not null default 0, wins integer not null default 0, championships integer not null default 0, primary key (season_id, team_id));
create table if not exists public.achievements (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, description text not null, created_at timestamptz not null default now());
create table if not exists public.player_achievements (user_id uuid not null references auth.users(id) on delete cascade, achievement_id uuid not null references public.achievements(id) on delete cascade, awarded_at timestamptz not null default now(), primary key (user_id, achievement_id));
create table if not exists public.team_achievements (team_id uuid not null references public.teams(id) on delete cascade, achievement_id uuid not null references public.achievements(id) on delete cascade, awarded_at timestamptz not null default now(), primary key (team_id, achievement_id));
alter table public.profiles enable row level security;
alter table public.teams enable row level security;
drop policy if exists profiles_public_directory_select on public.profiles;
create policy profiles_public_directory_select on public.profiles for select using (true);
drop policy if exists teams_public_directory_select on public.teams;
create policy teams_public_directory_select on public.teams for select using (true);
drop policy if exists team_members_public_directory_select on public.team_members;
create policy team_members_public_directory_select on public.team_members for select using (true);
alter table public.seasons enable row level security;
alter table public.player_season_rankings enable row level security;
alter table public.team_season_rankings enable row level security;
alter table public.achievements enable row level security;
alter table public.player_achievements enable row level security;
alter table public.team_achievements enable row level security;
drop policy if exists seasons_public_select on public.seasons;
create policy seasons_public_select on public.seasons for select using (true);
drop policy if exists player_rankings_public_select on public.player_season_rankings;
create policy player_rankings_public_select on public.player_season_rankings for select using (true);
drop policy if exists team_rankings_public_select on public.team_season_rankings;
create policy team_rankings_public_select on public.team_season_rankings for select using (true);
drop policy if exists achievements_public_select on public.achievements;
create policy achievements_public_select on public.achievements for select using (true);
drop policy if exists player_achievements_public_select on public.player_achievements;
create policy player_achievements_public_select on public.player_achievements for select using (true);
drop policy if exists team_achievements_public_select on public.team_achievements;
create policy team_achievements_public_select on public.team_achievements for select using (true);
grant select on public.profiles, public.teams, public.team_members, public.seasons, public.player_season_rankings, public.team_season_rankings, public.achievements, public.player_achievements, public.team_achievements to anon, authenticated;
insert into public.seasons(name, starts_at, ends_at) values ('August 2026', '2026-08-01', '2026-09-01') on conflict (name) do nothing;
