import Link from "next/link";
import { notFound } from "next/navigation";
import { getPublicPlayer } from "@/lib/community/data";
import { ReportPlayerModal } from "@/components/reports/ReportPlayerModal";

export default async function PlayerPage({ params }: { params: Promise<{ username: string }> }) {
  const { username } = await params; const player = await getPublicPlayer(username); if (!player) notFound();
  return <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><Link href="/leaderboard" className="text-sm text-arena-accent hover:underline">← Leaderboard</Link><section className="glass-card mt-6 rounded-2xl p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-5"><div className="flex items-center gap-5">{player.avatar_url ? <img src={player.avatar_url} alt="" className="h-24 w-24 rounded-2xl object-cover" /> : <div className="flex h-24 w-24 items-center justify-center rounded-2xl bg-cyan-400/15 font-display text-3xl font-bold text-arena-accent">{(player.display_name || player.username).slice(0, 1).toUpperCase()}</div>}<div><p className="text-sm uppercase tracking-[0.25em] text-arena-accent">Player profile</p><h1 className="font-display text-4xl font-bold text-white">{player.display_name || player.username}</h1><p className="text-arena-muted">@{player.username} · {player.region || "Region not set"}</p></div></div><ReportPlayerModal reportedUserId={player.id} /></div><p className="mt-6 max-w-2xl text-arena-muted">{player.bio || "This player has not added a bio yet."}</p><div className="mt-6 grid gap-3 sm:grid-cols-4"><Stat label="Riot ID" value={player.riot_id || "Not linked"} /><Stat label="Trust score" value={String(player.trust_score ?? 50)} /><Stat label="Rank" value={player.current_rank || "Unranked"} /><Stat label="Favorite game" value={player.favorite_game || "VALORANT"} /></div></section></main>;
}
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white/[0.04] p-3"><p className="text-xs text-arena-muted">{label}</p><p className="mt-1 font-semibold text-white">{value}</p></div>; }
